spring.application.name=smart-courier-management-system

#configure database (mysql)
spring.datasource.url=jdbc:mysql://localhost:3306/courier_db?allowPublicKeyRetrieval=true&useSSL=false

# Database Username
spring.datasource.username=root

# Database Password
spring.datasource.password=Harsh@12345

# JDBC Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Hibernate Configuration
# Automatically update tables
spring.jpa.hibernate.ddl-auto=update

# Show SQL in console
spring.jpa.show-sql=true

# Format SQL
spring.jpa.properties.hibernate.format_sql=true

# Spring prints mappings in console i
logging.level.org.springframework.web=DEBUG

#security config
#spring.security.user.name = harsh
#spring.security.user.password = pass

#JWT Secret key
jwt.secretKey=thisissecretkeyforfgkfkfhhftyejttdkffjkjhuiydghjwttokenjfddfjhfjksdfhhl